sudo: false

language: c

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - valgrind

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install valgrind; fi

install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..

script:
  - valgrind --leak-check=full --track-origins=yes bin/jay test/hello.jay -ohello --echo
