sudo: false
language: c
dist: trusty

install:
  - mkdir build && cd build
  - cmake ..
  - make all

script: ctest --verbose

matrix:
  include:
    # default
    - os: linux
    - os: osx

    # coverage build
    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      install:
        - mkdir build && cd build
        - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
        - make all
      script:
        - ctest --verbose
      after_success:
        - cd .. && bash <(curl -s https://codecov.io/bash) -xgcov-5

    # osx
    - os: osx
      osx_image: xcode7.3
      compiler: clang
    - os: osx
      osx_image: xcode8.3
      compiler: clang

    # gcc
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - gcc-4.9
            - libclang-5.0-dev
    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - gcc-5
            - libclang-5.0-dev
    - os: linux
      compiler: gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - gcc-6
            - libclang-5.0-dev
    - os: linux
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - gcc-7
            - libclang-5.0-dev

    # clang
    - os: linux
      compiler: clang-3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.5
          packages:
            - libclang-3.5-dev
            - clang-3.5
    - os: linux
      compiler: clang-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages:
            - libclang-3.6-dev
            - clang-3.6
    - os: linux
      compiler: clang-3.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages:
            - libclang-3.8-dev
            - clang-3.8
    - os: linux
      compiler: clang-3.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - libclang-3.9-dev
            - clang-3.9
    - os: linux
      compiler: clang-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - libclang-4.0-dev
            - clang-4.0
