sudo: false

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - clang-3.4
      - clang++-3.4
      - bison
      - flex

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4" CC="clang-3.4"; fi

install:
  - ${CC} --version ; ${CXX} --version;
  - bison --version
  - ./autogen.sh

before_script:
  - mkdir build
  - cd build
  - ../configure

script: make