dist: trusty
sudo: false
group: beta

language: cpp

compiler:
  - gcc
  - clang

install:
  - ./autogen.sh

before_script:
  - mkdir build
  - cd build
  - ../configure

script:
  - ${CC} --version
  - ${CXX} --version
  - bison --version
  - automake --version
  - make check