sudo: false

language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

before_install:
  - wget --no-check-certificate http://ftp.gnu.org/gnu/bison/bison-3.0.4.tar.gz
  - mkdir $HOME/bison
  - tar -xf bison-3.0.4.tar.gz; cd bison-3.0.4; ./configure --prefix=$HOME/bison; make -j 4 install; cd $PWD/..;
  - export PATH=$HOME/bison/bin:$PATH
  - wget http://ftp.gnu.org/gnu/automake/automake-1.15.tar.xz
  - tar xvf automake-1.15.tar.xz; cd automake-1.15; ./configure --prefix=/usr && make; sudo make install; cd $PWD/..;
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

install:
  - ./autogen.sh

before_script:
  - mkdir build
  - cd build
  - ../configure

script:
  - ${CC} --version
  - ${CXX} --version
  - bison --version
  - automake --version
  - make