sudo: false
language: c
os: linux
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - libllvm5.0
      - llvm-5.0
      - llvm-5.0-dev
      - libclang-5.0-dev
      - clang-5.0
      - libclang1-5.0
      - libclang-5.0-dev

install:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .

script: ctest --verbose
