dist: trusty
sudo: false
group: beta

language: cc

compiler:
  - g++
  - clang

install:
  - ./autogen.sh

install:
  - mkdir build
  - cd build
  - cmake ..

script:
  - ${CC} --version
  - make check
