sudo: false

language: c

addons:
  apt:
    packages:
      - valgrind

compiler:
  - gcc
  - clang

install:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ls -la
  - cd .. && valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes bin/jay test/hello.jay -ohello --echo
