sudo: false

language: c

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install valgrind; fi

install:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..

script:
  - valgrind --leak-check=full --track-origins=yes bin/jay test/hello.jay -ohello

matrix:
  include:
    - os: linux
      compiler: gcc-4.9
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - valgrind
            - gcc-4.9

    - os: linux
      compiler: gcc-5
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - valgrind
            - gcc-5

    - os: linux
      compiler: gcc-6
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - cmake-data
            - valgrind
            - gcc-6

    - os: linux
      compiler: clang-3.5
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - cmake
            - cmake-data
            - valgrind
            - clang-3.5

    - os: linux
      compiler: clang-3.6
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - cmake-data
            - valgrind
            - clang-3.6

    - os: linux
      compiler: clang-3.7
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - cmake
            - cmake-data
            - valgrind
            - clang-3.7

    - os: linux
      compiler: clang-3.8
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - cmake
            - cmake-data
            - valgrind
            - clang-3.8

    - os: linux
      compiler: clang-3.9
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - cmake
            - cmake-data
            - valgrind
            - clang-3.9

    - os: linux
      compiler: clang-4.0
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-4.0
          packages:
            - cmake
            - cmake-data
            - valgrind
            - clang-4.0

    - os: osx
      osx_image: xcode6.4
      compiler: clang

    - os: osx
      osx_image: xcode7.3
      compiler: clang

    - os: osx
      osx_image: xcode8.3
      compiler: clang
