version: "{build}"

platform:
  - Win32
  - x64

environment:
  MSVC_DEFAULT_OPTIONS: ON

configuration:
  - Debug
  - Release

environment:
  matrix:
    - msvc: 'Visual Studio 10 2010'
    - msvc: 'Visual Studio 11 2012'
    - msvc: 'Visual Studio 12 2013'
    - msvc: 'Visual Studio 14 2015'
    - msvc: 'Visual Studio 14 2015'
    - msvc: 'Visual Studio 14 2015'
    - msvc: 'Visual Studio 14 2015'

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\jay

branches:
  only:
    - master

install:
  - git submodule update --init --recursive

before_build:
  - cmd: cd C:\projects\jay
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=%msvc%
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=%msvc% Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: C:\projects\jay\build\jay.sln
  verbosity: quiet

test: off
