# Specify version format
version: "{build}"

# Operating system (build VM template)
os: Visual Studio 2015

# build platform, i.e. Win32 (instead of x86), x64, Any CPU. This setting is optional.
platform: 
  - Win32
  - x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# scripts that are called at very beginning, before repo cloning
init:
  - cmd: cmake --version
  - cmd: msbuild /version

# clone directory
clone_folder: C:\projects\jay

# branches to build
branches:
  only:
    - master

# scripts to run before build
before_build:
  - cmd: cd C:\projects\jay
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%"

build:
  project: C:\projects\jay\build\jay.sln # path to Visual Studio solution or project
  parallel: true                           # enable MSBuild parallel builds
  verbosity: quiet                         # MSBuild verbosity level (quiet|minimal|normal|detailed)

test: off
#test_script:
#  - cmd: ctest --build-config %configuration% --parallel 4 --output-on-failure
