version: "{build}"

os: Visual Studio 2015

platform:
  - Win32
  - x64

environment:
  MSVC_DEFAULT_OPTIONS: ON

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\jay

branches:
  only:
    - master

install:
  - git submodule update --init --recursive

before_build:
  - cmd: cd C:\projects\jay
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G "NMake Makefiles" ..

build:
  project: C:\projects\jay\build\jay.sln
  verbosity: normal

test: off
