version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
    - msvc: Visual Studio 10 2010
    - msvc: Visual Studio 11 2012
    - msvc: Visual Studio 12 2013
    - msvc: Visual Studio 14 2015

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

matrix:
  exclude:
    - msvc: Visual Studio 10 2010
      platform: x64
    - msvc: Visual Studio 9 2008
      platform: x64

build:
  verbosity: minimal

before_build:
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=%msvc%
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=%msvc% Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% ..

test_script:
  - cmd: ctest -VV
