version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
    - msvc: Visual Studio 14 2015
    - msvc: Visual Studio 12 2013
    - msvc: Visual Studio 11 2012
    - msvc: Visual Studio 10 2010
    - msvc: Visual Studio 9 2008

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

matrix:
  exclude:
    - msvc: Visual Studio 10 2010
      platform: x64
    - msvc: Visual Studio 9 2008
      platform: x64

build:
  verbosity: minimal

before_build:
  - ps: |
    Write-Output "Configuration: %configuration%"
    Write-Output "Platform: %platform%"
    $generator = %msvc%
    if (%platform% -eq "x64") {
      $generator = "$generator Win64"
    }

before_build:
  - ps: |
    md build -Force | Out-Null
    cd build
    & cmake -G "$generator" -DCMAKE_BUILD_TYPE=%configuration% ..
    if ($LastExitCode -ne 0) {
      throw "Exec: $ErrorMessage"
    }
    & cmake --build . --config %configuration%
    if ($LastExitCode -ne 0) {
      throw "Exec: $ErrorMessage"
    }


test_script:
  - ps: |
    & ctest -C %configuration% --output-on-failure
    if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
    }
